### ISSUE TITLE
App Release

### ISSUE THREAD

**Issue by vishalscodes** [tylerbwong/stack#158] opened 2024-04-13 01:41 UTC
Please release this app to F-Droid or IzzyOnDroid.

**Comment by tylerbwong** [comment] 2024-04-13 05:35
Duplicate of #140 and #110. There is a non-Google variant available to download on the [releases page](https://github.com/tylerbwong/stack/releases).

**Closed by tylerbwong** 2024-04-13 05:35 UTC

**Comment by vishalscodes** [comment] 2024-04-13 14:31
I asked as it would probably help for the updating stuff, I already have that apk.
