### ISSUE TITLE
No way to ask questions (?)

### ISSUE THREAD

**Issue by sbeve72** [tylerbwong/stack#131] opened 2023-02-26 23:34 UTC
I wasn't able to find a way to create questions in any of the forums. I am sorry if it's there but I couldn't find it. If so, please help me find it.

It will be nice to have a way to ask questions

**Comment by tylerbwong** [comment] 2023-02-26 23:45
Closing as a duplicate of #118

It's in the works!

**Closed** 2023-02-26 23:45 UTC
